### ISSUE TITLE
TypeError: Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by tdhz77** [JackAdams/meteor-accounts-ldap#11]
This is an error I get only in production. For this app, I have set LDAP.tryDBFirst = true; Could this be the reason for this error?   

[192.168.5.29] Unable to create user
[192.168.5.29] { [Error: Match error: Expected plain object]
 message: 'Match error: Expected plain object',
  path: '',
  sanitizedError: 
   { [Error: Match failed [400]]
     error: 400,
     reason: 'Match failed',
     details: undefined,
     message: 'Match failed [400]',
     errorType: 'Meteor.Error' },
  errorType: 'Match.Error' }
New user _id: undefined
[192.168.5.29] Exception while invoking method 'login' TypeError: Cannot read property '_id' of undefined
    at Object.<anonymous> (server/ldap.js:37:27)
    at packages/babrahams_accounts-ldap/ldap_server.js:431:1
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at Function._.each._.forEach (packages/underscore/packages/underscore.js:134:1)
    at [object Object].Package (packages/babrahams_accounts-ldap/ldap_server.js:430:1)
    at accounts_server.js:462:32
    at tryLoginMethod (accounts_server.js:239:14)
    at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
    at [object Object].methods.login (accounts_server.js:522:27)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)

**Comment by JackAdams** [comment]
Yes, sorry!  I introduced a bug in 0.4.4 when fixing a couple of other bugs.  Regression fixed in 0.4.5.

**Comment by tdhz77** [comment]
Got it going, thank you so much!
