### ISSUE TITLE
what happens if server is down

### ISSUE THREAD

**Issue by tosinek** [JackAdams/meteor-accounts-ldap#28]
Our LDAP server is down, so when I try to login with a new account or enter incorrect password (so that the tryDBfirst fails), after some time I get ```"LDAP bind failed with error:" {}``` . 
It throws on ```throw new Meteor.Error('ldap-error', 'ldapjs client reported an error', error);```
but "error" is not giving out any useful information. The whole process than forces application restart

```
packages/babrahams_accountsldap.js:197
    throw new Meteor.Error('ldap-error', 'ldapjs client reported an error', error);
    ^
Error: ldapjs client reported an error [ldap-error]
    at Client.<anonymous> (packages/babrahams_accountsldap.js:197:11)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at Backoff.<anonymous> (/mnt/c/meteor/slm-frontend/.meteor/local/isopacks/babrahams_accountsldap/npm/node_modules/ldapjs/lib/client/client.js:1228:12)
    at emitOne (events.js:116:13)
    at Backoff.emit (events.js:211:7)
    at Backoff.backoff (/mnt/c/meteor/slm-frontend/.meteor/local/isopacks/babrahams_accountsldap/npm/node_modules/backoff/lib/backoff.js:41:14)
    at /mnt/c/meteor/slm-frontend/.meteor/local/isopacks/babrahams_accountsldap/npm/node_modules/ldapjs/lib/client/client.js:1214:15
    at f (/mnt/c/meteor/slm-frontend/.meteor/local/isopacks/babrahams_accountsldap/npm/node_modules/once/once.js:17:25)
    at Socket.onResult (/mnt/c/meteor/slm-frontend/.meteor/local/isopacks/babrahams_accountsldap/npm/node_modules/ldapjs/lib/client/client.js:1016:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

I could not set up Meteor debugging (missing sourcemaps for local packages?), so I don't know what to do next. Is there any option to just fail the login process with "incorrect password"?

My LDAP setup (it was for OpenLDAP and worked well while the server was on):
```
LDAP.searchField = 'uid'
LDAP.searchValueType = 'username'
LDAP.logging = true
LDAP.tryDBFirst = true
LDAP.filter = function(isEmailAddress, usernameOrEmail, FQDN) {
  return '(&(samaccountname=' + usernameOrEmail + ')(objectClass=person))';
}
LDAP.generateSettings = function(request) {
  const settingsLdap = Settings.findOne({ type: 'ldap' })
  return {
    serverDn: settingsLdap.baseDN,
    serverUrl: `${settingsLdap.useSSL ? 'ldaps' : ldap'}://${settingsLdap.hostname}:${settingsLdap.port}`,
    whiteListedFields: [ "displayName", "cn", "givenName", "mail", "memberOf"],
  }
}
```

**Comment by JackAdams** [comment]
Sorry for the late reply.  I've had the same thing happen when the LDAP server is not available and it puts the server in a state requiring a restart.  It's frustrating, but happens infrequently enough that I haven't looked into handling that particular error better. Also, I haven't really touched the core code of this package (which was a fork of `hive:accounts-ldap`), as my knowledge of LDAP and the `ldapjs` library is superficial at best.

That said, you're asking more about having an option to ignore the LDAP requests altogether, which (for me, at least) would an easier thing to do.  If you'd like to put together a PR, I'd be happy to review and merge it.

**Comment by tosinek** [comment]
Cool, I will do the PR. Removing the respective [Meteor.Error line](https://github.com/JackAdams/meteor-accounts-ldap/blob/e9b9980ff6ae8ee319003b6d401ab26bc1f3fb80/ldap_server.js#L173) solved the problem for now.

I will need a good working package for our LDAP requirements, so I am now thinking more like using a stub of your package for starters, but replacing ldapjs with something that is maintained and also add an option to disable LDAP login optinally (or switch between local and LDAP login explicitly).

**Comment by JackAdams** [comment]
Nice. I’d be very interested in that package when it’s ready. (I’d rather not rely on ldapjs either, if possible.)
